const db = globalThis.__B44_DB__ || { auth:{ isAuthenticated: async()=>false, me: async()=>null }, entities:new Proxy({}, { get:()=>({ filter:async()=>[], get:async()=>null, create:async()=>({}), update:async()=>({}), delete:async()=>({}) }) }), integrations:{ Core:{ UploadFile:async()=>({ file_url:'' }) } } };

const LMU_BASE = 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Le Mans Ultimate\\UserData\\Liveries';

export const VEHICLES = [
  {
    id: 'aston_martin_gt3',
    name: 'Aston Martin Vantage GT3',
    class: 'GT3',
    uvMap: '/lmutemplates/AstonMartinVantage_2025_UV.png',
    classStickers: '/lmutemplates/TOP_GT3_AstonMartinVantage_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Aston Martin Vantage GT3`,
  },
  {
    id: 'corvette_z06_lmgt3',
    name: 'Corvette Z06 LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/CorvetteZ06LMGT3_2025_UV.png',
    classStickers: '/lmutemplates/TOP_CorvetteZ06LMGT3_2025_.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Corvette Z06 LMGT3`,
  },
  {
    id: 'ferrari_296_lmgt3',
    name: 'Ferrari 296 LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/Ferrari296LMGT3_2025_UV.png',
    classStickers: '/lmutemplates/TOP_Ferrari296LMGT3_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Ferrari 296 LMGT3`,
  },
  {
    id: 'bmw_m4_lmgt3',
    name: 'BMW M4 LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/BMWM4LMGT3_2025_UV.png',
    classStickers: '/lmutemplates/TOP GT3_BMWM4LMGT3_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\BMW M4 LMGT3`,
  },
  {
    id: 'ford_mustang_lmgt3',
    name: 'Ford Mustang LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/FordMustangLMGT3_2025_UV.png',
    classStickers: '/lmutemplates/TOP_FordMustangLMGT3_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Ford Mustang LMGT3`,
  },
  {
    id: 'lamborghini_huracan_lmgt3',
    name: 'Lamborghini Huracan LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/LamborghiniHuracan_UV.png',
    classStickers: '/lmutemplates/TOP_LamborghiniHuracan.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Lamborghini Huracan LMGT3`,
  },
  {
    id: 'lexus_rcf_lmgt3',
    name: 'Lexus RCF LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/LexusRCF_2025_UV.png',
    classStickers: '/lmutemplates/TOP_LexusRCF_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Lexus RCF LMGT3`,
  },
  {
    id: 'mclaren_720evo_lmgt3',
    name: 'McLaren 720 EVO LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/McLaren720EVO_2025_UV.png',
    classStickers: '/lmutemplates/TOP_McLaren720EVO_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\McLaren 720 EVO LMGT3`,
  },
  {
    id: 'mercedes_amg_lmgt3',
    name: 'Mercedes AMG LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/MercedesAMG_2025_UV.png',
    classStickers: '/lmutemplates/TOP_MercedesAMG_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Mercedes AMG LMGT3`,
  },
  {
    id: 'porsche_911_lmgt3',
    name: 'Porsche 911 LMGT3',
    class: 'LMGT3',
    uvMap: '/lmutemplates/Porsche911LMGT3R_2025_UV.png',
    classStickers: '/lmutemplates/TOP_Porsche911LMGT3R_2025.png',
    canvasWidth: 4096,
    canvasHeight: 4096,
    liveryPath: `${LMU_BASE}\\Porsche 911 LMGT3`,
  }
];

export const BASE_COLOURS = [
  { label: 'Racing White', value: '#FFFFFF' },
  { label: 'Jet Black', value: '#0A0A0A' },
  { label: 'Gulf Blue', value: '#1E6FA8' },
  { label: 'Gulf Orange', value: '#F47920' },
  { label: 'British Racing Green', value: '#004225' },
  { label: 'Ferrari Red', value: '#CC0000' },
  { label: 'Porsche Silver', value: '#9B9EA4' },
  { label: 'Aston Racing Yellow', value: '#F5C400' },
  { label: 'Martini Blue', value: '#002D72' },
  { label: 'Rothmans Blue', value: '#003399' },
  { label: 'Candy Apple Red', value: '#FF0800' },
  { label: 'Midnight Navy', value: '#0D1B2A' },
  { label: 'Carbon Dark', value: '#1A1A1A' },
  { label: 'Champagne Gold', value: '#C5A028' },
  { label: 'Custom…', value: 'custom' },
];
